version: '3'
services:
  backendexpress:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: server-express
    links:
      - database
    ports:
      - "3000:3002"
    networks:
      backend:
        ipv4_address: 10.5.0.6
    
  database:
    networks:
      backend:
        ipv4_address: 10.5.0.5
    container_name: database
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sucesso
      MYSQL_DATABASE: trybecashdb
    ports:
      - "33070:3306"

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
